[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Redirect for single page app (if needed)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  condition = "Not from=/api/*"
  
# If you want multiple pages, comment out the redirect above