pipeline:
  name: Build soho-showcase
  identifier: Build_FerMoha2177_soho_showcase_1752684626753
  projectIdentifier: SOHOSHOWCASE
  orgIdentifier: default
  stages:
    - stage:
        name: Build and Deploy
        identifier: Build_Deploy
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Starting Build Proc msg
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: echo "Starting Build Process for Soho-Showcase"
              - step:
                  type: Run
                  name: Install Dependencies
                  identifier: Install_Dependencies
                  spec:
                    shell: Sh
                    command: npm ci
              - step:
                  type: Run
                  name: Running Build Scripts
                  identifier: Running_Build_Script
                  spec:
                    shell: Sh
                    command: npm run build
              - step:
                  type: Run
                  name: Verify Build Output
                  identifier: Verify_Build
                  spec:
                    shell: Sh
                    command: |
                      ls -la dist/
                      echo "Build completed successfully!"
              - step:
                  type: Run
                  name: Deploy to Netlify
                  identifier: Deploy_Netlify
                  spec:
                    shell: Sh
                    command: |
                      # Install Node 20
                      curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
                      sudo apt-get install -y nodejs

                      # Verify Node version
                      echo "Node version check:"
                      /usr/bin/node --version
                      /usr/bin/npm --version

                      # Install netlify-cli globally
                      /usr/bin/npm install -g netlify-cli

                      # Find where netlify was installed
                      echo "Finding netlify CLI location:"
                      which netlify
                      /usr/bin/npm list -g netlify-cli

                      # Deploy using the correct path (usually in /usr/lib/node_modules/.bin/)
                      echo "Deploying to Netlify..."
                      $(which netlify) deploy \
                        --dir=dist \
                        --prod \
                        --auth="$NETLIFY_TOKEN" \
                        --site="$NETLIFY_SITE_ID" \
                        --message="Automated deployment from Harness CI/CD"
                    envVariables:
                      NETLIFY_TOKEN: <+secrets.getValue("netlify_access_token90")>
                      NETLIFY_SITE_ID: <+secrets.getValue("NETLIFY_SITE_ID")>
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1752684594713
        repoName: FerMoha2177/soho-showcase
        build: <+input>
