pipeline:
  name: Build soho-showcase
  identifier: Build_FerMoha2177_soho_showcase_1752684626753
  projectIdentifier: SOHOSHOWCASE
  orgIdentifier: default
  stages:
    - stage:
        name: Build and Deploy
        identifier: Build_Deploy
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Starting Build Proc msg
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: echo "Starting Build Process for Soho-Showcase"
              - step:
                  type: Run
                  name: Install Dependencies
                  identifier: Install_Dependencies
                  spec:
                    shell: Sh
                    command: npm ci
              - step:
                  type: Run
                  name: Running Build Scripts
                  identifier: Running_Build_Script
                  spec:
                    shell: Sh
                    command: npm run build
              - step:
                  type: Run
                  name: Verify Build Output
                  identifier: Verify_Build
                  spec:
                    shell: Sh
                    command: |
                      ls -la dist/
                      echo "Build completed successfully!"
              - step:
                  type: Run
                  name: Deploy to Netlify
                  identifier: Deploy_Netlify
                  spec:
                    shell: Sh
                    command: |
                      # Use Node 20 for netlify-cli compatibility
                      curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
                      sudo apt-get install -y nodejs

                      # Install netlify-cli
                      npm install -g netlify-cli

                      # Login and deploy directly with auth token
                      echo "Deploying to Netlify..."
                      netlify deploy \
                        --dir=dist \
                        --prod \
                        --auth="$NETLIFY_TOKEN" \
                        --site="$NETLIFY_SITE_ID" \
                        --message="Automated deployment from Harness CI/CD"
                    envVariables:
                      NETLIFY_TOKEN: <+secrets.getValue("netlify_access_token90")>
                      NETLIFY_SITE_ID: <+secrets.getValue("NETLIFY_SITE_ID")>
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1752684594713
        repoName: FerMoha2177/soho-showcase
        build: <+input>
